apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ANZSIC
  description: The ANZSIC Search API
  annotations:
    backstage.io/spectral-ruleset-url: https://raw.githubusercontent.com/SPSCommerce/sps-api-standards/main/sps-api-standards.spectral.yml
spec:
  type: openapi
  lifecycle: production
  owner: petstore@example.com
  definition: 
    $text: https://swagger-ui.portals.eu.org/docs/ANZSIC-Search.yml

