apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: AXWAY-1.4
  description: The Axway Admin API version 1.4
  annotations:
    backstage.io/spectral-ruleset-url: https://raw.githubusercontent.com/baloise-incubator/spectral-ruleset/main/zalando.yml
spec:
  type: openapi
  lifecycle: production
  owner: petstore@example.com
  definition: 
    $text: https://swagger-ui.portals.eu.org/docs/axway.json
