apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: BabyNames
  description: The BabyNames API
  annotations:
    backstage.io/spectral-ruleset-url: https://raw.githubusercontent.com/SPSCommerce/sps-api-standards/main/sps-api-standards.spectral.yml
spec:
  type: openapi
  lifecycle: production
  owner: babynames@example.com
  definition: 
    $text: https://swagger-ui.portals.eu.org/docs/Popular-baby-names-vic.yml
