apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: petstore
  description: The Petstore API
spec:
  type: openapi
  lifecycle: production
  owner: petstore@example.com
  definition: 
    $text: https://swagger-ui.portals.eu.org/docs/Popular-baby-names-vic.yml
